import React from "react";
import { addCapaEvidence, assignCapa, changeCapaStatus, createCapa, decideAlert, getAlerts, getCapas, reopenCapa, submitCapaVerification, verifyCapa } from "../api/governance.js";
import { html } from "../ui.js";
import { PageTitle } from "./AnalyzePage.js";

export function ActionsPage({ actor }) {
  const [capas, setCapas] = React.useState([]); const [alerts, setAlerts] = React.useState([]); const [error, setError] = React.useState("");
  const [form, setForm] = React.useState({ report_id: "", alert_id: "", title: "", description: "", action_type: "corrective", priority: "high", due_date: "" });
  async function load() { try { const [c, a] = await Promise.all([getCapas(), getAlerts()]); setCapas(c); setAlerts(a); setError(""); } catch (err) { setError(err.message); } }
  React.useEffect(() => { load(); }, [actor.role]);
  async function run(action) { try { await action(); await load(); } catch (err) { setError(err.message); } }
  async function create(event) { event.preventDefault(); await run(() => createCapa({ ...form, due_date: form.due_date || null })); }
  return html`<div className="space-y-6"><${PageTitle} eyebrow="ACTIONS" title="Corrective and preventive actions" subtitle="CAPAs follow a controlled assignment, execution, verification, and closure workflow. No action closes automatically." />
    <div className="rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm"><b>Acting as:</b> ${actor.name} · ${actor.role.replaceAll("_", " ")}</div>${error ? html`<div className="error-box">${error}</div>` : null}
    ${["HSE_OFFICER", "HSE_MANAGER", "ADMIN"].includes(actor.role) ? html`<form className="panel" onSubmit=${create}><p className="eyebrow">CREATE CAPA</p><div className="mt-4 grid gap-3 md:grid-cols-2"><${Input} label="Linked report ID" value=${form.report_id} onChange=${(v) => setForm({ ...form, report_id: v })} /><${Input} label="Linked alert ID" value=${form.alert_id} onChange=${(v) => setForm({ ...form, alert_id: v })} /><${Input} label="Title" value=${form.title} required=${true} onChange=${(v) => setForm({ ...form, title: v })} /><${Input} label="Description" value=${form.description} required=${true} onChange=${(v) => setForm({ ...form, description: v })} /><${Select} label="Action type" value=${form.action_type} values=${["corrective", "preventive", "investigation"]} onChange=${(v) => setForm({ ...form, action_type: v })} /><${Select} label="Priority" value=${form.priority} values=${["low", "medium", "high", "critical"]} onChange=${(v) => setForm({ ...form, priority: v })} /><${Input} label="Due date" type="date" value=${form.due_date} onChange=${(v) => setForm({ ...form, due_date: v })} /></div><button className="primary-button mt-4">Create CAPA</button></form>` : null}
    <section className="panel"><div className="flex justify-between"><div><p className="eyebrow">WORKFLOW</p><h2 className="mt-2 text-xl font-semibold">Safety actions</h2></div><button className="secondary-button" onClick=${load}>Refresh</button></div><div className="mt-5 space-y-4">${capas.map((capa) => html`<article key=${capa.capa_id} className="rounded-2xl border border-slate-200 p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold text-cyan-700">${capa.capa_id}</p><h3 className="mt-1 font-bold">${capa.title}</h3><p className="mt-1 text-sm text-slate-600">${capa.description}</p></div><span className=${`rounded-full px-3 py-1 text-xs font-bold uppercase ${capa.is_overdue ? "bg-rose-100 text-rose-700" : "bg-slate-100 text-slate-700"}`}>${capa.effective_status.replaceAll("_", " ")}</span></div><div className="mt-3 flex flex-wrap gap-3 text-xs text-slate-500"><span>Priority: ${capa.priority}</span><span>Owner: ${capa.owner_name || "Unassigned"}</span><span>Due: ${capa.due_date ? String(capa.due_date).slice(0, 10) : "Not set"}</span><span>Evidence: ${capa.evidence.length}</span></div><div className="mt-4 flex flex-wrap gap-2">${capa.status === "open" || capa.status === "reopened" ? html`<button className="secondary-button" onClick=${() => { const owner = window.prompt("Owner name", "Site Supervisor"); if (owner) run(() => assignCapa(capa.capa_id, { owner_name: owner, owner_role: "SITE_SUPERVISOR" })); }}>Assign</button>` : null}${capa.status === "assigned" ? html`<button className="secondary-button" onClick=${() => run(() => changeCapaStatus(capa.capa_id, "in_progress", "Work started."))}>Start work</button>` : null}${capa.status === "in_progress" ? html`<button className="secondary-button" onClick=${() => { const note = window.prompt("Evidence/note"); if (note) run(() => addCapaEvidence(capa.capa_id, { evidence_type: "note", note })); }}>Add evidence</button><button className="primary-button" onClick=${() => { const note = window.prompt("Completion note"); if (note) run(() => submitCapaVerification(capa.capa_id, note)); }}>Submit for verification</button>` : null}${capa.status === "awaiting_verification" && ["HSE_OFFICER", "HSE_MANAGER", "ADMIN"].includes(actor.role) ? html`<button className="primary-button" onClick=${() => { const note = window.prompt("Verification note"); if (note) run(() => verifyCapa(capa.capa_id, note)); }}>Verify and close</button>` : null}${capa.status === "closed" && ["HSE_OFFICER", "HSE_MANAGER", "ADMIN"].includes(actor.role) ? html`<button className="secondary-button" onClick=${() => { const note = window.prompt("Reason to reopen"); if (note) run(() => reopenCapa(capa.capa_id, note)); }}>Reopen</button>` : null}</div></article>`)}</div>${!capas.length ? html`<p className="py-8 text-center text-sm text-slate-500">No CAPAs have been created.</p>` : null}</section>
    <section className="panel"><p className="eyebrow">ACTIONABLE ALERTS</p><div className="mt-4 space-y-3">${alerts.map((alert) => html`<article className="rounded-xl border border-amber-200 bg-amber-50 p-4" key=${alert.alert_id}><div className="flex justify-between"><b>${alert.title}</b><span className="text-xs font-bold uppercase">${alert.status}</span></div><p className="mt-1 text-xs text-slate-600">${alert.alert_id} · Report ${alert.report_id}</p>${["HSE_OFFICER", "HSE_MANAGER", "ADMIN"].includes(actor.role) && alert.status === "open" ? html`<div className="mt-3 flex flex-wrap gap-2"><button className="secondary-button" onClick=${() => run(() => decideAlert(alert.alert_id, "acknowledge"))}>Acknowledge</button><button className="secondary-button" onClick=${() => run(() => decideAlert(alert.alert_id, "escalate", "Escalated by HSE review."))}>Escalate</button><button className="secondary-button" onClick=${() => { const reason = window.prompt("Dismissal reason"); if (reason) run(() => decideAlert(alert.alert_id, "dismiss", reason)); }}>Dismiss</button><button className="primary-button" onClick=${() => setForm({ ...form, alert_id: alert.alert_id, report_id: alert.report_id || "", title: `Action for ${alert.title}`, description: "", priority: alert.severity === "critical" ? "critical" : "high" })}>Create CAPA</button></div>` : null}</article>`)}</div></section>
  </div>`;
}
function Input({ label, type = "text", value, onChange, required = false }) { return html`<label><span className="filter-label">${label}</span><input className="filter-control" type=${type} value=${value} required=${required} onChange=${(e) => onChange(e.target.value)} /></label>`; }
function Select({ label, value, values, onChange }) { return html`<label><span className="filter-label">${label}</span><select className="filter-control" value=${value} onChange=${(e) => onChange(e.target.value)}>${values.map((v) => html`<option key=${v} value=${v}>${v}</option>`)}</select></label>`; }
