import React from "react";
import { approveDocument, getDocument, getDocuments, retireDocument, uploadKnowledgeDocument } from "../api/governance.js";
import { getJobs } from "../api/phase3.js";
import { html } from "../ui.js";
import { PageTitle } from "./AnalyzePage.js";

export function KnowledgePage({ actor }) {
  const [documents, setDocuments] = React.useState([]); const [selected, setSelected] = React.useState(null); const [file, setFile] = React.useState(null); const [error, setError] = React.useState("");
  const [jobs, setJobs] = React.useState([]);
  const [meta, setMeta] = React.useState({ title: "", organization: "", version: "", effective_date: "", review_date: "", source_reference: "", supersedes_document_id: "" });
  async function load() { try { const [docs, allJobs] = await Promise.all([getDocuments(), getJobs()]); setDocuments(docs); setJobs(allJobs.filter((job) => job.job_type === "DOCUMENT_INDEXING")); setError(""); } catch (err) { setError(err.message); } }
  React.useEffect(() => { load(); const timer = window.setInterval(load, 3000); return () => window.clearInterval(timer); }, []);
  async function upload(event) { event.preventDefault(); if (!file) { setError("Select a PDF or TXT safety document."); return; } try { await uploadKnowledgeDocument(file, meta); setFile(null); await load(); } catch (err) { setError(err.message); } }
  async function open(id) { try { setSelected(await getDocument(id)); } catch (err) { setError(err.message); } }
  const canManage = ["HSE_OFFICER", "HSE_MANAGER", "ADMIN"].includes(actor.role);
  async function govern(action) { try { const doc = action === "approve" ? await approveDocument(selected.document_id) : await retireDocument(selected.document_id); setSelected({ ...selected, ...doc }); await load(); } catch (err) { setError(err.message); } }
  return html`<div className="space-y-6"><${PageTitle} eyebrow="KNOWLEDGE" title="Controlled safety document index" subtitle="Sources retain version history. Only approved documents effective on the observation date are eligible for grounded citations." />${error ? html`<div className="error-box">${error}</div>` : null}
    ${canManage ? html`<form className="panel" onSubmit=${upload}><p className="eyebrow">UPLOAD DRAFT</p><div className="mt-4 grid gap-3 md:grid-cols-3">${Object.entries(meta).map(([key, value]) => html`<label key=${key}><span className="filter-label">${key.replaceAll("_", " ")}</span>${key === "supersedes_document_id" ? html`<select className="filter-control" value=${value} onChange=${(e) => setMeta({ ...meta, [key]: e.target.value })}><option value="">New document</option>${documents.filter((doc) => doc.status === "APPROVED").map((doc) => html`<option key=${doc.document_id} value=${doc.document_id}>${doc.title} · v${doc.version || "?"}</option>`)}</select>` : html`<input className="filter-control" required=${["title", "organization"].includes(key)} type=${["effective_date", "review_date"].includes(key) ? "date" : "text"} value=${value} onChange=${(e) => setMeta({ ...meta, [key]: e.target.value })} />`}</label>`)}</div><input className="mt-4 block w-full rounded-xl border border-slate-200 p-3 text-sm" type="file" accept=".pdf,.txt" onChange=${(e) => setFile(e.target.files?.[0] || null)} /><button className="primary-button mt-4">Upload Draft & start indexing</button></form>` : null}
    ${jobs.some((job) => ["queued", "running"].includes(job.status)) ? html`<section className="panel"><p className="eyebrow">INDEXING JOBS</p>${jobs.filter((job) => ["queued", "running"].includes(job.status)).map((job) => html`<div className="mt-3" key=${job.job_id}><div className="flex justify-between text-xs"><b>${job.job_id}</b><span>${job.progress_current} / ${job.progress_total || "?"}</span></div><div className="mt-2 h-2 rounded bg-slate-100"><div className="h-full rounded bg-cyan-500" style=${{ width: `${job.progress_percent}%` }}></div></div></div>`)}</section>` : null}
    <div className="grid gap-5 lg:grid-cols-[0.7fr_1.3fr]"><section className="space-y-3">${documents.map((doc) => html`<button key=${doc.document_id} className="w-full rounded-2xl border border-slate-200 bg-white p-4 text-left" onClick=${() => open(doc.document_id)}><div className="flex justify-between gap-2"><p className="text-xs font-bold text-cyan-700">${doc.document_id}</p><span className=${`rounded-full px-2 py-0.5 text-[10px] font-bold ${doc.status === "APPROVED" ? "bg-emerald-100 text-emerald-700" : "bg-slate-100"}`}>${doc.status}</span></div><h2 className="mt-1 font-bold">${doc.title}</h2><p className="mt-1 text-xs text-slate-500">${doc.organization} · v${doc.version || "unspecified"} · ${doc.chunk_count} chunks · ${doc.indexing_status}</p></button>`)}</section><section className="panel">${selected ? html`<div className="flex flex-wrap justify-between gap-3"><div><p className="eyebrow">SOURCE PREVIEW</p><h2 className="mt-2 text-xl font-bold">${selected.title}</h2><p className="mt-1 text-sm text-slate-500">v${selected.version || "unspecified"} · ${selected.status} · Effective ${selected.effective_date || "unspecified"}</p></div><div className="flex gap-2">${selected.status === "DRAFT" ? html`<button className="primary-button" disabled=${selected.indexing_status !== "completed"} onClick=${() => govern("approve")}>Approve</button>` : null}${["APPROVED", "SUPERSEDED"].includes(selected.status) ? html`<button className="secondary-button" onClick=${() => govern("retire")}>Retire</button>` : null}</div></div><p className="mt-3 text-sm text-slate-500">Reference: ${selected.source_reference || "Uploaded local source"}</p><div className="mt-5 max-h-[520px] space-y-3 overflow-y-auto">${(selected.chunks || []).map((chunk) => html`<article className="rounded-xl bg-slate-50 p-4" key=${chunk.chunk_id}><p className="text-xs font-bold">${chunk.section}${chunk.page ? ` · Page ${chunk.page}` : ""}</p><p className="mt-2 text-sm leading-6 text-slate-600">${chunk.text}</p></article>`)}</div>` : html`<p className="py-16 text-center text-sm text-slate-500">Choose a document to inspect its governed source chunks.</p>`}</section></div>
  </div>`;
}
